/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function flySipInitSdkJs(internal: string, external: string, appId: string, appKey: string, username: string, password: string, uesrId: string, isHttps: number): number

export declare function plus100(input: number): number
